name: CI
on: [pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Update theme
        # (Optional)If you have the theme added as submodule, you can pull it and use the most updated version
        run: git submodule update --init --recursive

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.85.0"

      - name: Build
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        run: hugo

       - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}
          external_repository: pallavirawat/pallavirawat.github.io
          publish_dir: ./public
          #   keep_files: true
          user_name: palavirawat
          user_email: me@rawatpallavi.com
          publish_branch: gh-pages-try
          full_commit_message: ${{ github.event.head_commit.message }}
          cname: rawatpallavi.com
